### ISSUE TITLE
ProcessField and ProcessTemplate breadcrumbs got broken in 0.3.5

### ISSUE THREAD

**Issue by ivangretsky** [Toutouwai/BreadcrumbDropdowns#10]
Good day, @Toutouwai !
It seems like the new cool updates broke the ProcessField and ProcessTemplate breadcrumbs:
![изображение](https://user-images.githubusercontent.com/6697626/124345634-d9e9c480-dbe2-11eb-9136-2f97bffdb067.png)

**Comment by Toutouwai** [comment]
Thanks, I couldn't see that layout bug in my browser (Chrome) but I found that the module was producing some invalid markup which was probably the cause of what you're seeing. Should be fixed now in v0.3.6.

**Comment by ivangretsky** [comment]
It works right now in my Firefox. Thank you!
