### ISSUE TITLE
Links to Access and Users when editing a user

### ISSUE THREAD

**Issue by adrianbj** [Toutouwai/BreadcrumbDropdowns#6]
Hi @Toutouwai - I think it would be nice if the "Access" and "Users" links went to /processwire/access/ and /processwire/users respectively. At the moment, they are kinda broken.

![image](https://user-images.githubusercontent.com/871211/61673625-18f80700-aca5-11e9-8a36-2c0b0bf5b59e.png)

Thanks!

**Comment by Toutouwai** [comment]
Should be improved in v0.1.21 - the breadcrumb links are the now same as the standard AdminThemeUikit breadcrumbs apart from the last extra dropdown breadcrumb.

**Comment by adrianbj** [comment]
Much better - thanks!
