### ISSUE TITLE
Respect $config->pageEdit['editCrumbs'] setting

### ISSUE THREAD

**Issue by ivangretsky** [Toutouwai/BreadcrumbDropdowns#8]
Good day @Toutouwai and thanks for the great module!

There is a [$config option](https://github.com/processwire/processwire/blob/d8945198f4a6a60dab23bd0462e8a6285369dcb9/wire/config.php#L1322) for the pageEdit process, which allows to modify breadcrumbs behavior (change links to edit instead of open in tree). BreadcrumbDropdowns seems to not take that into account. Could you please change that so that we could use edit links and your module together?

**Comment by Toutouwai** [comment]
I've added support for this in v0.3.5.
FYI: you always have edit links to pages in the breadcrumbs and their child pages via the dropdowns (that's one of the main points of the module) so if you have BreadcrumbDropdowns installed you're arguably better off with `editCrumbs` left at the default `false` and then you have the best of both worlds available: edit links via the dropdowns and Page List links via the breadcrumbs.

**Comment by ivangretsky** [comment]
Thanks for the quick fix! And thanks for the suggestion. I guess the client will decide. But now we got options to choose from)
