### ISSUE TITLE
Wrong dropdown position with AdminThemeUikit style rock

### ISSUE THREAD

**Issue by ivangretsky** [Toutouwai/BreadcrumbDropdowns#9]
Good day @Toutouwai !

I am trying the recently added [AdminThemeUikit rock style](https://processwire.com/blog/posts/pw-3.0.179/). BreadcrumbDropdowns works, but the dropdown is positioned in the wrong part of the page: it is in the left top part instead of being under the arrow. Probably some `position: relative` missing or something like that. Could you plaese suggest how to fix it and or fix it the core of the module if possible?

**Comment by Toutouwai** [comment]
I can't reproduce that. Do you have the latest version of BreadcrumbDropdowns installed? Latest is v0.3.4 at the time I'm writing this.

![2021-07-03_102651](https://user-images.githubusercontent.com/1538852/124333900-a2324b00-dbe9-11eb-8e33-502bed3a3919.png)

**Comment by adrianbj** [comment]
Just to say that it also seems to be working fine for me as well.

**Comment by ivangretsky** [comment]
Ahh! Had 0.3.3. Upgrading fixed it. Thank you!
